# Generated by Django 4.2.7 on 2023-11-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_alter_student_encodings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Encodings',
            field=models.TextField(null=True),
        ),
    ]
