# Generated by Django 4.2.7 on 2023-11-09 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_alter_student_encodings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='roll_no',
            field=models.CharField(max_length=9, primary_key=True, serialize=False),
        ),
    ]
