# Generated by Django 4.2.7 on 2023-11-09 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_course_degree'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='student',
            field=models.ManyToManyField(related_name='courses', to='database.student'),
        ),
    ]
